version: '3'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - backend_dir:/app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ardeco
      DB_USER: root
      DB_PASSWORD: mnw4xav-bud*eha*DCE

  db:
    image: mysql:latest 
    restart: always
    environment:
      MYSQL_DATABASE: ardeco
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  dbdata:
    external: true
  backend_dir:
