version: '3'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - backend_dir:/app
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ardeco
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  dbdata:
  backend_dir:
