name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install npm dependencies
      working-directory: ./server
      run: npm install
    - name: Build the Docker image
      working-directory: ./server
      run: docker build . --file Dockerfile --tag ardeco-server:$(date +%s)
