name: Docker Image CI

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        working-directory: ./server
        run: docker build . --file Dockerfile --tag ardeco-server:$(date +%s)
