name: Tests and Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./server
        run: npm install

      - name: Run tests
        working-directory: ./server
        run: npm run test

      - name: Build the Docker image
        working-directory: ./server
        run: docker build . --file Dockerfile --tag ardeco-server:$(date +%s)
